apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.fullname" . }}-sparkadmin-service-account
  labels:
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.sparkadminServiceAccount.serviceAccount.annotations | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-sparkadmin-deployment
  labels:
    app: sparkadmin
  {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.sparkadminDeployment.replicas }}
  selector:
    matchLabels:
      app: sparkadmin
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: sparkadmin
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.sparkadminDeployment.sparkadmin.image.repository }}:{{ .Values.sparkadminDeployment.sparkadmin.image.tag
          | default .Chart.AppVersion }}
        name: sparkadmin
        ports:
        - containerPort: 8080
        resources: {}
      serviceAccountName: {{ include "chart.fullname" . }}-sparkadmin-service-account
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-sparkadmin-service
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sparkadminService.type }}
  selector:
    app: sparkadmin
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.sparkadminService.ports | toYaml | nindent 2 }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "chart.fullname" . }}-sparkadmin-ui-virtualservice
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  gateways:
  - kubeflow/kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /spark-admin/
    rewrite:
      uri: /spark-admin/
    route:
    - destination:
        host: sparkadmin-service.dev.svc.cluster.local
        port:
          number: 80
    timeout: 300s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-pod-listing-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - list
  - get
  - watch
  - create
- apiGroups:
  - kubeflow.org
  resources:
  - profiles
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart.fullname" . }}-pod-listing-role-binding
  labels:
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "chart.fullname" . }}-pod-listing-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "chart.fullname" . }}-sparkadmin-service-account'
  namespace: '{{ .Release.Namespace }}'
