apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-chart.fullname" . }}-streamlitapp
  labels:
    app: streamlitapp
  {{- include "my-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.streamlitapp.type }}
  selector:
    app: streamlitapp
    {{- include "my-chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.streamlitapp.ports | toYaml | nindent 2 }}
