apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dlnp-ops-be.fullname" . }}-cluster-role-binding
  labels:
    app: ops-be
  {{- include "dlnp-ops-be.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "dlnp-ops-be.fullname" . }}-cluster-role'
subjects:
- kind: ServiceAccount
  name: default
  namespace: '{{ .Release.Namespace }}'
