apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nstarx-kubeflow-core.fullname" . }}-clusterrole
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
