apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nstarx-kubeflow-core.fullname" . }}-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "nstarx-kubeflow-core.fullname" . }}-serviceaccount
    namespace: default
roleRef:
  kind: ClusterRole
  name: {{ include "nstarx-kubeflow-core.fullname" . }}-clusterrole
  apiGroup: rbac.authorization.k8s.io
