{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubeflow-operator.fullname" . }}-admin
  labels:
    {{- include "kubeflow-operator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubeflow-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  {{- if .Values.rbac.useClusterAdmin }}
  name: cluster-admin
  {{- else }}
  name: {{ include "kubeflow-operator.fullname" . }}-role
  {{- end }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}