apiVersion: v1
kind: ServiceAccount
metadata:
  name: fl-admin
  namespace: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-admin
  namespace: dev
  labels:
    app: fl-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fl-admin
  template:
    metadata:
      labels:
        app: fl-admin
    spec:
      serviceAccountName: fl-admin
      containers:
      - name: admin
        image: padrian2s/fl-admin:latest
        ports:
        - containerPort: 8080
---
# sparkadmin-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fl-admin
  namespace: dev
spec:
  selector:
    app: fl-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fl-admin
  namespace: dev
spec:
  gateways:
  - kubeflow/kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /flower-admin/
    rewrite:
        uri: /flower-admin/
    route:
    - destination:
        port:
          number: 80
        host: fl-admin.dev.svc.cluster.local
    timeout: 300s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fl-admin-listing-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fl-listing-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fl-admin-listing-role
subjects:
- kind: ServiceAccount
  name: fl-admin
  namespace: dev
---
